services:
  sandbox:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/sandbox
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    env_file:
      - .env
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token=''
